### ISSUE TITLE
When i try to run make command it sshowed me following error

### ISSUE THREAD

**Issue by richardwing121** [tomochain/proxy#3]
make
go build -o proxy *.go
main.go:5:2: cannot find package "github.com/inconshreveable/log15" in any of:
        /usr/local/go/src/github.com/inconshreveable/log15 (from $GOROOT)
        /root/work/src/github.com/inconshreveable/log15 (from $GOPATH)
main.go:6:2: cannot find package "github.com/rs/cors" in any of:
        /usr/local/go/src/github.com/rs/cors (from $GOROOT)
        /root/work/src/github.com/rs/cors (from $GOPATH)
main.go:7:2: cannot find package "github.com/tomochain/proxy/cache" in any of:
        /usr/local/go/src/github.com/tomochain/proxy/cache (from $GOROOT)
        /root/work/src/github.com/tomochain/proxy/cache (from $GOPATH)
main.go:8:2: cannot find package "github.com/tomochain/proxy/cache/lru" in any of:
        /usr/local/go/src/github.com/tomochain/proxy/cache/lru (from $GOROOT)
        /root/work/src/github.com/tomochain/proxy/cache/lru (from $GOPATH)
main.go:9:2: cannot find package "github.com/tomochain/proxy/config" in any of:
        /usr/local/go/src/github.com/tomochain/proxy/config (from $GOROOT)
        /root/work/src/github.com/tomochain/proxy/config (from $GOPATH)
main.go:10:2: cannot find package "github.com/tomochain/proxy/healthcheck" in any of:
        /usr/local/go/src/github.com/tomochain/proxy/healthcheck (from $GOROOT)
        /root/work/src/github.com/tomochain/proxy/healthcheck (from $GOPATH)
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by thanhson1085** [comment]
wrong $GOPATH
